backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/Home.vue"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}